import { useEffect, useRef, useState } from 'react';

// Project locations: [name, lat, lng]
const PROJECT_LOCATIONS = [
  { name: 'Isla Negra, Chile', lat: -33.44, lng: -71.69, home: true },
  { name: 'Santiago, Chile', lat: -33.45, lng: -70.67 },
  { name: 'Valparaíso, Chile', lat: -33.04, lng: -71.62 },
  { name: 'Antofagasta, Chile', lat: -23.65, lng: -70.40 },
  { name: 'Temuco, Chile', lat: -38.73, lng: -72.59 },
  { name: 'Buenos Aires, Argentina', lat: -34.60, lng: -58.38 },
  { name: 'Lima, Peru', lat: -12.04, lng: -77.03 },
  { name: 'Bogotá, Colombia', lat: 4.71, lng: -74.07 },
  { name: 'Mexico City, Mexico', lat: 19.43, lng: -99.13 },
  { name: 'Madrid, Spain', lat: 40.42, lng: -3.70 },
];

const THEMES = {
  light: {
    // Real NASA Blue Marble texture — no polygon fill needed
    globeTexture: 'https://unpkg.com/three-globe/example/img/earth-day.jpg',
    bumpTexture: 'https://unpkg.com/three-globe/example/img/earth-topology.png',
    continentCap: 'rgba(0,0,0,0)',        // transparent — texture handles land
    continentSide: 'rgba(0,0,0,0)',
    continentStroke: 'rgba(0,0,0,0)',
    atmosphere: '#6BAED6',
    arcColors: ['#2B5C3F', '#4A6FA5'],
    pointHome: '#C04A2E',
    pointOther: '#2B5C3F',
  },
  dark: {
    globeTexture: '',                      // generated by makeOceanTexture()
    bumpTexture: '',
    continentCap: 'rgba(43,92,63,0.5)',
    continentSide: 'rgba(43,92,63,0.12)',
    continentStroke: 'rgba(78,158,113,0.35)',
    atmosphere: '#4E9E71',
    arcColors: ['#00d4aa', '#3b82f6'],
    pointHome: '#f59e0b',
    pointOther: '#00d4aa',
  },
};

// Generate a realistic ocean gradient texture
const makeOceanTexture = (isDark: boolean): string => {
  const size = 512;
  const canvas = document.createElement('canvas');
  canvas.width = size; canvas.height = size;
  const ctx = canvas.getContext('2d')!;

  if (isDark) {
    // Deep ocean night: abyssal blues
    const base = ctx.createLinearGradient(0, 0, size, size);
    base.addColorStop(0,   '#071525');
    base.addColorStop(0.4, '#0a1e32');
    base.addColorStop(0.7, '#08192a');
    base.addColorStop(1,   '#050f1c');
    ctx.fillStyle = base;
    ctx.fillRect(0, 0, size, size);

    // Subtle depth variation noise
    const deep = ctx.createRadialGradient(size*0.3, size*0.4, 0, size*0.3, size*0.4, size*0.6);
    deep.addColorStop(0,   'rgba(15,45,75,0.4)');
    deep.addColorStop(1,   'rgba(0,0,0,0)');
    ctx.fillStyle = deep;
    ctx.fillRect(0, 0, size, size);
  } else {
    // Realistic daylight ocean: deep blue to shallow teal
    const base = ctx.createLinearGradient(0, 0, size, size);
    base.addColorStop(0,   '#1B6FA8');
    base.addColorStop(0.3, '#1A6298');
    base.addColorStop(0.6, '#155880');
    base.addColorStop(1,   '#0E4A72');
    ctx.fillStyle = base;
    ctx.fillRect(0, 0, size, size);

    // Shallow coastal glow (lighter near top)
    const shallow = ctx.createRadialGradient(size*0.5, size*0.2, 0, size*0.5, size*0.5, size*0.7);
    shallow.addColorStop(0,   'rgba(64,155,195,0.35)');
    shallow.addColorStop(0.5, 'rgba(30,110,165,0.15)');
    shallow.addColorStop(1,   'rgba(0,0,0,0)');
    ctx.fillStyle = shallow;
    ctx.fillRect(0, 0, size, size);

    // Deep trench overlay
    const trench = ctx.createRadialGradient(size*0.6, size*0.7, 0, size*0.6, size*0.7, size*0.5);
    trench.addColorStop(0,   'rgba(8,55,95,0.3)');
    trench.addColorStop(1,   'rgba(0,0,0,0)');
    ctx.fillStyle = trench;
    ctx.fillRect(0, 0, size, size);
  }

  return canvas.toDataURL();
};

export default function Globe() {
  const mountRef = useRef<HTMLDivElement>(null);
  const globeRef = useRef<any>(null);
  const [loaded, setLoaded] = useState(false);

  const isDarkTheme = () =>
    document.documentElement.getAttribute('data-theme') === 'dark';

  const getThemeColors = () =>
    isDarkTheme() ? THEMES.dark : THEMES.light;

  useEffect(() => {
    if (!mountRef.current) return;

    let globe: any;
    let animationId: number;

    const initGlobe = async () => {
      const GlobeGL = (await import('globe.gl')).default;

      const t = getThemeColors();

      const arcs = PROJECT_LOCATIONS.filter((p) => !p.home).map((p) => ({
        startLat: -33.44,
        startLng: -71.69,
        endLat: p.lat,
        endLng: p.lng,
        label: p.name,
        color: t.arcColors,
      }));

      const points = PROJECT_LOCATIONS.map((p) => ({
        lat: p.lat,
        lng: p.lng,
        name: p.name,
        color: p.home ? t.pointHome : t.pointOther,
        altitude: p.home ? 0.05 : 0.02,
        radius: p.home ? 0.6 : 0.35,
      }));

      // Fetch world countries GeoJSON (pre-converted, no dependencies needed)
      const geoRes = await fetch(
        'https://cdn.jsdelivr.net/gh/holtzy/D3-graph-gallery@master/DATA/world.geojson'
      );
      const countries = await geoRes.json();

      const dark = isDarkTheme();
      const textureUrl = dark ? makeOceanTexture(true) : t.globeTexture;

      globe = GlobeGL()(mountRef.current!)
        .globeImageUrl(textureUrl)
        .bumpImageUrl(dark ? '' : t.bumpTexture)
        .backgroundColor('rgba(0,0,0,0)')
        .showAtmosphere(true)
        .atmosphereColor(t.atmosphere)
        .atmosphereAltitude(0.15)
        .polygonsData(countries.features)
        .polygonCapColor(() => t.continentCap)
        .polygonSideColor(() => t.continentSide)
        .polygonStrokeColor(() => t.continentStroke)
        .polygonAltitude(dark ? 0.005 : 0.001)
        .arcColor('color')
        .arcDashLength(0.4)
        .arcDashGap(0.2)
        .arcDashAnimateTime(2500)
        .arcStroke(0.5)
        .arcAltitudeAutoScale(0.4)
        .arcsData(arcs)
        .pointColor('color')
        .pointAltitude('altitude')
        .pointRadius('radius')
        .pointsMerge(false)
        .pointsData(points)
        .pointLabel('name')
        .width(mountRef.current!.clientWidth)
        .height(mountRef.current!.clientHeight);

      globe.onGlobeReady(() => {
        globe.controls().autoRotate = true;
        globe.controls().autoRotateSpeed = 0.4;
        globe.controls().enableZoom = false;
        globe.controls().enablePan = false;
        globe.pointOfView({ lat: -20, lng: -65, altitude: 2.2 }, 0);

        setLoaded(true);

        // React to theme toggle in real time
        const observer = new MutationObserver(() => {
          const nt = getThemeColors();
          const nowDark = isDarkTheme();
          globe
            .globeImageUrl(nowDark ? makeOceanTexture(true) : nt.globeTexture)
            .bumpImageUrl(nowDark ? '' : nt.bumpTexture)
            .atmosphereColor(nt.atmosphere)
            .polygonCapColor(() => nt.continentCap)
            .polygonSideColor(() => nt.continentSide)
            .polygonStrokeColor(() => nt.continentStroke)
            .polygonAltitude(nowDark ? 0.005 : 0.001);
        });
        observer.observe(document.documentElement, {
          attributes: true,
          attributeFilter: ['data-theme'],
        });
      });

      globeRef.current = globe;

      // Resize handler
      const handleResize = () => {
        if (!mountRef.current) return;
        globe.width(mountRef.current.clientWidth);
        globe.height(mountRef.current.clientHeight);
      };
      window.addEventListener('resize', handleResize);

      return () => {
        window.removeEventListener('resize', handleResize);
        cancelAnimationFrame(animationId);
      };
    };

    initGlobe();

    return () => {
      globeRef.current = null;
    };
  }, []);

  return (
    <div className="relative w-full h-full">
      {/* Glow ring behind globe */}
      <div
        className="absolute inset-0 m-auto w-[70%] h-[70%] rounded-full pointer-events-none"
        style={{
          background:
            'radial-gradient(circle, rgba(0,212,170,0.08) 0%, transparent 70%)',
          filter: 'blur(40px)',
        }}
      />
      <div
        ref={mountRef}
        className="w-full h-full"
        style={{ opacity: loaded ? 1 : 0, transition: 'opacity 1s ease' }}
      />
      {!loaded && (
        <div className="absolute inset-0 flex items-center justify-center">
          <div
            className="w-16 h-16 rounded-full border-2 border-[#00d4aa22] border-t-[#00d4aa]"
            style={{ animation: 'spin 1s linear infinite' }}
          />
        </div>
      )}
    </div>
  );
}
